# Generated by Django 2.2.1 on 2019-07-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('primary', 'primary'), ('mandetory', 'mandetory'), ('optional', 'optional')], max_length=60)),
                ('field_datatype', models.CharField(choices=[('AutoField', 'AutoField'), ('BigAutoField', 'BigAutoField'), ('BigIntegerField', 'BigIntegerField'), ('BinaryField', 'BinaryField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('FileField', 'FileField'), ('DecimalField', 'DecimalField'), ('DurationField', 'DurationField'), ('ImageField', 'ImageField'), ('EmailField', 'EmailField'), ('FloatField', 'FloatField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('SlugField', 'SlugField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField')], max_length=60)),
                ('proof_doc', models.CharField(choices=[('Drving liecense', 'Drving liecense'), ('Aadhar', 'Aadhar'), ('SSC Certificate', 'SSC Certificate'), ('Passport', 'Passport'), ('PAN card', 'PAN card'), ('Any Govt. Issued Proof', 'Any Govt. Issued Proof')], max_length=60)),
                ('policy', models.ManyToManyField(to='cKYC_Policy.Policy')),
            ],
        ),
    ]
