# Generated by Django 2.2.1 on 2019-07-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyfields',
            name='policy',
        ),
        migrations.AddField(
            model_name='policyfields',
            name='policy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cKYC_Policy.Policy'),
        ),
    ]
