# Generated by Django 2.2.1 on 2019-07-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0002_auto_20190730_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfields',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cKYC_Policy.Policy'),
        ),
    ]
