# Generated by Django 2.2.1 on 2019-07-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0004_auto_20190730_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policyfield',
        ),
        migrations.AddField(
            model_name='policyfield',
            name='policy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cKYC_Policy.Policy'),
            preserve_default=False,
        ),
    ]
