# Generated by Django 2.2.1 on 2019-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0005_auto_20190730_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfield',
            name='proof_doc',
            field=models.CharField(blank=True, choices=[('Drving liecense', 'Drving liecense'), ('Aadhar', 'Aadhar'), ('SSC Certificate', 'SSC Certificate'), ('Passport', 'Passport'), ('PAN card', 'PAN card'), ('Any Govt. Issued Proof', 'Any Govt. Issued Proof')], max_length=60),
        ),
    ]
