# Generated by Django 2.2.1 on 2019-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0008_policy_policy_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfield',
            name='field_datatype',
            field=models.CharField(choices=[('text', 'TextField'), ('date', 'DateField'), ('datetime', 'DateTimeField'), ('image', 'ImageField'), ('email', 'EmailField'), ('file', 'FileField'), ('number', 'IntegerField'), ('textarea', 'TextAreaField'), ('time', 'TimeField'), ('url', 'URLField'), ('select', 'SelectDropDownField')], max_length=60),
        ),
    ]
