# Generated by Django 2.2.1 on 2019-08-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_Policy', '0014_auto_20190826_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='policy_conditions',
            new_name='policy_description',
        ),
    ]
