# Generated by Django 2.2.1 on 2019-07-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_userprofile', '0002_auto_20190731_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
