# Generated by Django 2.2.1 on 2019-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_userprofile', '0003_auto_20190731_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_name',
            field=models.CharField(max_length=50),
        ),
    ]
