# Generated by Django 2.2.1 on 2019-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cKYC_userprofile', '0005_userkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='private_key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='public_key',
            field=models.CharField(max_length=30),
        ),
    ]
